# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'room_v1alfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1000, 537)
        mainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        mainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(105, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(358, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.odalarButton = QtWidgets.QPushButton(self.frame_top_menus)
        self.odalarButton.setMinimumSize(QtCore.QSize(0, 40))
        self.odalarButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.odalarButton.setObjectName("odalarButton")
        self.verticalLayout_4.addWidget(self.odalarButton)
        self.girisButton = QtWidgets.QPushButton(self.frame_top_menus)
        self.girisButton.setMinimumSize(QtCore.QSize(0, 40))
        self.girisButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.girisButton.setObjectName("girisButton")
        self.verticalLayout_4.addWidget(self.girisButton)
        self.infoButton = QtWidgets.QPushButton(self.frame_top_menus)
        self.infoButton.setMinimumSize(QtCore.QSize(0, 40))
        self.infoButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.infoButton.setObjectName("infoButton")
        self.verticalLayout_4.addWidget(self.infoButton)
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.odalarPage = QtWidgets.QWidget()
        self.odalarPage.setObjectName("odalarPage")
        self.label_2 = QtWidgets.QLabel(self.odalarPage)
        self.label_2.setGeometry(QtCore.QRect(0, 480, 102, 38))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.odalarList = QtWidgets.QListWidget(self.odalarPage)
        self.odalarList.setGeometry(QtCore.QRect(0, 0, 256, 441))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.odalarList.setFont(font)
        self.odalarList.setStyleSheet("color: rgb(255, 255, 255);")
        self.odalarList.setObjectName("odalarList")
        self.doktorAdi = QtWidgets.QLabel(self.odalarPage)
        self.doktorAdi.setGeometry(QtCore.QRect(280, 50, 571, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doktorAdi.setFont(font)
        self.doktorAdi.setStyleSheet("color: rgb(255, 255, 255);")
        self.doktorAdi.setObjectName("doktorAdi")
        self.odaBilgi = QtWidgets.QLabel(self.odalarPage)
        self.odaBilgi.setGeometry(QtCore.QRect(280, 100, 571, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.odaBilgi.setFont(font)
        self.odaBilgi.setStyleSheet("color: rgb(255, 255, 255);")
        self.odaBilgi.setObjectName("odaBilgi")
        self.stackedWidget.addWidget(self.odalarPage)
        self.girisPage = QtWidgets.QWidget()
        self.girisPage.setObjectName("girisPage")
        self.label = QtWidgets.QLabel(self.girisPage)
        self.label.setGeometry(QtCore.QRect(0, 480, 181, 38))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(238, 238, 236);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.kullaniciAdiLabel = QtWidgets.QLabel(self.girisPage)
        self.kullaniciAdiLabel.setGeometry(QtCore.QRect(220, 120, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.kullaniciAdiLabel.setFont(font)
        self.kullaniciAdiLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.kullaniciAdiLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.kullaniciAdiLabel.setObjectName("kullaniciAdiLabel")
        self.sifreLabel = QtWidgets.QLabel(self.girisPage)
        self.sifreLabel.setGeometry(QtCore.QRect(470, 120, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.sifreLabel.setFont(font)
        self.sifreLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.sifreLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sifreLabel.setObjectName("sifreLabel")
        self.doktorGirisButton = QtWidgets.QPushButton(self.girisPage)
        self.doktorGirisButton.setGeometry(QtCore.QRect(360, 310, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doktorGirisButton.setFont(font)
        self.doktorGirisButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.doktorGirisButton.setObjectName("doktorGirisButton")
        self.usrInput = QtWidgets.QLineEdit(self.girisPage)
        self.usrInput.setGeometry(QtCore.QRect(220, 190, 161, 25))
        self.usrInput.setStyleSheet("color: rgb(255, 255, 255);")
        self.usrInput.setObjectName("usrInput")
        self.pswInput = QtWidgets.QLineEdit(self.girisPage)
        self.pswInput.setGeometry(QtCore.QRect(470, 190, 161, 25))
        self.pswInput.setStyleSheet("color: rgb(255, 255, 255);")
        self.pswInput.setInputMask("")
        self.pswInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pswInput.setObjectName("pswInput")
        self.stackedWidget.addWidget(self.girisPage)
        self.infoPage = QtWidgets.QWidget()
        self.infoPage.setObjectName("infoPage")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.infoPage)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.infoPage)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.stackedWidget.addWidget(self.infoPage)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Oda Kontrol"))
        self.odalarButton.setText(_translate("mainWindow", "Odalar"))
        self.girisButton.setText(_translate("mainWindow", "Doktor Giriş"))
        self.infoButton.setText(_translate("mainWindow", "Bilgi"))
        self.label_2.setText(_translate("mainWindow", "Odalar"))
        self.odalarList.setSortingEnabled(False)
        self.doktorAdi.setText(_translate("mainWindow", "Doktor:"))
        self.odaBilgi.setText(_translate("mainWindow", "Bilgi:"))
        self.label.setText(_translate("mainWindow", "Doktor Giriş"))
        self.kullaniciAdiLabel.setText(_translate("mainWindow", "Doktor No"))
        self.sifreLabel.setText(_translate("mainWindow", "Şifre"))
        self.doktorGirisButton.setText(_translate("mainWindow", "Giriş"))
        self.label_3.setText(_translate("mainWindow", "CyprusRobotics © 2021 Oda Kontrol v0.0.1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
